export const ACTION_TYPES = {
    COUNTER: {
        INCREASE: 'INCREASE',
        INCREASE_SUCCESS: 'INCREASE_SUCCESS',
        DECREASE: 'DECREASE',
        DECREASE_SUCCESS: 'DECREASE_SUCCESS',
    },
}